---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: debian-9.3
  - name: debian-9.2
  - name: debian-9.1
  - name: centos-7.1
  - name: centos-7.2
  - name: centos-7.3
  - name: centos-7.4
  - name: oracle-7
  - name: oracle-7.3
  - name: oracle-7.4


suites:
  - name: default
    run_list:
      - recipe[postgresql::default]
    attributes:
