---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos/7
    driver:
      box: centos/7
      box_url: https://app.vagrantup.com/centos/boxes/7
      network: 
      - ["private_network", {ip: "192.168.33.34"}]

suites:
  - name: default
    run_list:
      - recipe[report::default]
    attributes:
